import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <header className="">
          <nav className="flex justify-end bg-green-900 p-4 gap-4">
            <Link href="/">Home</Link>
            <Link href="/products">Shop</Link>
            <Link href="/login">Login</Link>
            <Link href="/admin">Admin</Link>
          </nav>
        </header>

        <main className="flex-1 bg-gray-700">
          {children}
        </main>

        <footer className="flex justify-center bg-green-700">
          <h1>@Ecommerce sa BSMGT/ISTR21/ISOOPR</h1>
        </footer>
      </body>
    </html>
  );
}
